name: "Setup environment"
description: "Prepare repository and all dependencies"

runs:
    using: "composite"
    steps:
        - name: Use pnpm
          uses: pnpm/action-setup@v4
          with:
              run_install: false

        - name: Use Node
          uses: actions/setup-node@v4
          with:
              node-version: 20
              cache: "pnpm"
              registry-url: "https://npm.pkg.github.com"
              scope: "@defi-wonderland"

        - name: Use foundry
          uses: foundry-rs/foundry-toolchain@v1
          with:
              version: nightly
